# Build Script for SGAGS using GHA

name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Software
        run: |
          sudo apt -y install dos2unix


      - name: Set up Python V3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install domain2idna
          pip3 install PyFunceble-dev --pre
          pip3 install ultimate-hosts-blacklist-whitelist-dev


      - name: Run build
        shell: bash
        run: |
          ./scripts/travis-commit.sh

